import type { Product } from '@/types/product';

export const products: Product[] = [
  {
    id:          '1',
    name:        'Sworn In Hoodie',
    slug:        'sworn-in-hoodie',
    price:       50,
    category:    'hoodies',
    imageSrc:    '/images/Sworn-In-Hoodie-black.jpg',
    badge:       null,
    description: 'A heavyweight pullover hoodie built to last. Worn by people who mean what they say.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Grey', 'Navy'],
    colorImages: {
      Black: '/images/Sworn-In-Hoodie-black.jpg',
      Grey:  '/images/Sworn-In-Hoodie-black.jpg',
      Navy:  '/images/Sworn-In-Hoodie-black.jpg',
    },
  },
  {
    id:          '2',
    name:        'Stressed the F Out Hoodie',
    slug:        'stressed-the-f-out-hoodie',
    price:       50,
    category:    'hoodies',
    imageSrc:    '/images/Stressed-the-F-Out-Hoodie-black.jpg',
    badge:       null,
    description: 'Bold graphic hoodie. Heavy, warm, and unapologetic.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Grey', 'Navy'],
    colorImages: {
      Black: '/images/Stressed-the-F-Out-Hoodie-black.jpg',
      Grey:  '/images/Stressed-the-F-Out-Hoodie-black.jpg',
      Navy:  '/images/Stressed-the-F-Out-Hoodie-black.jpg',
    },
  },
  {
    id:          '3',
    name:        'Sworn In Long Sleeve T-Shirt',
    slug:        'sworn-in-long-sleeve',
    price:       30,
    category:    'long-sleeves',
    imageSrc:    '/images/Sworn-In-Long-Sleeve-T-Shirt-black.jpg',
    badge:       null,
    description: 'Clean long sleeve tee with the Sworn In logo. Comfortable fit, quality fabric.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Blue', 'Red'],
    colorImages: {
      Black: '/images/Sworn-In-Long-Sleeve-T-Shirt-black.jpg',
      Blue:  '/images/Sworn-In-Long-Sleeve-T-Shirt-black.jpg',
      Red:   '/images/Sworn-In-Long-Sleeve-T-Shirt-black.jpg',
    },
  },
  {
    id:          '4',
    name:        'Stressed the F Out Long Sleeve T-Shirt',
    slug:        'stressed-the-f-out-long-sleeve',
    price:       30,
    category:    'long-sleeves',
    imageSrc:    '/images/Stressed-the-F-Out-Long-Sleeve-T-Shirt-light-grey.jpg',
    badge:       null,
    description: 'Long sleeve tee with a bold distressed graphic. Makes a statement without trying.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Light Grey', 'Red'],
    colorImages: {
      Black:        '/images/Stressed-the-F-Out-Long-Sleeve-T-Shirt-light-grey.jpg',
      'Light Grey': '/images/Stressed-the-F-Out-Long-Sleeve-T-Shirt-light-grey.jpg',
      Red:          '/images/Stressed-the-F-Out-Long-Sleeve-T-Shirt-light-grey.jpg',
    },
  },
  {
    id:          '5',
    name:        'Sworn In Short Sleeve T-Shirt',
    slug:        'sworn-in-short-sleeve',
    price:       25,
    category:    'tshirts',
    imageSrc:    '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
    badge:       null,
    description: 'The everyday tee. Simple, clean, and built to hold up.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Dark Grey', 'Light Grey', 'Red', 'Royal Blue'],
    colorImages: {
      Black:        '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
      'Dark Grey':  '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
      'Light Grey': '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
      Red:          '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
      'Royal Blue': '/images/Sworn-In-Short-Sleeve-T-Shirt-black.jpg',
    },
  },
  {
    id:          '6',
    name:        'Stressed the F Out Short Sleeve T-Shirt',
    slug:        'stressed-the-f-out-short-sleeve',
    price:       25,
    category:    'tshirts',
    imageSrc:    '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
    badge:       null,
    description: 'Bold graphic tee with a distressed print. Exactly what it says.',
    sizes:       ['S', 'M', 'L', 'XL', '2XL'],
    colors:      ['Black', 'Dark Grey', 'Light Grey', 'Red', 'Royal Blue'],
    colorImages: {
      Black:        '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
      'Dark Grey':  '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
      'Light Grey': '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
      Red:          '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
      'Royal Blue': '/images/Stressed-the-F-Out-Short-Sleeve-T-Shirt-black.jpg',
    },
  },
  {
    id:          '7',
    name:        'Sworn In Hat',
    slug:        'sworn-in-hat',
    price:       30,
    category:    'headwear',
    imageSrc:    '/images/Sworn-In-Hat-black.jpg',
    badge:       null,
    description: 'Structured snapback with embroidered Sworn In logo.',
    sizes:       ['One Size'],
    colors:      [],
    colorImages: {},
  },
  {
    id:          '8',
    name:        'Sworn In Beanie',
    slug:        'sworn-in-beanie',
    price:       20,
    category:    'headwear',
    imageSrc:    '/images/Sworn-In-Beanie-navy.jpg',
    badge:       null,
    description: 'Embroidered beanie. Warm, clean, and to the point.',
    sizes:       ['One Size'],
    colors:      [],
    colorImages: {},
  },
  {
    id:          '9',
    name:        'American Flag Beanie',
    slug:        'american-flag-beanie',
    price:       20,
    category:    'headwear',
    imageSrc:    '/images/American-Flag-Beanie-navy.jpg',
    badge:       null,
    description: 'Navy beanie with an embroidered American flag patch.',
    sizes:       ['One Size'],
    colors:      [],
    colorImages: {},
  },
];

export const getProductBySlug = (slug: string): Product | null =>
  products.find((p) => p.slug === slug) ?? null;

export const getProductsByCategory = (category: string): Product[] =>
  products.filter((p) => p.category === category);

export const getFeaturedProducts = (): Product[] =>
  products.filter((p) =>
    ['sworn-in-hat', 'sworn-in-beanie', 'sworn-in-hoodie',
     'sworn-in-long-sleeve', 'sworn-in-short-sleeve'].includes(p.slug)
  );
